name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Dependencies
        run: yarn --prefer-offline # See - https://stackoverflow.com/a/62244232

      - name: Bootstrap lerna
        run: lerna bootstrap

      - name: Build Packages
        run: lerna run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo --tag-format='v\${version}'
